### ISSUE TITLE
add and customize Readme.md to project

### ISSUE THREAD

**Issue by JuniorN1** [JuniorN1/Api-pokemon-and-digimons#18]
you can show the project proposal, which showing data of Pokemons and Digimons with type, name, evolution, etc...
a short tutorial for other users to run the project on personal machines,
and add an invitation for all users who wanna collaborate with the project!

**Comment by varunwho** [comment]
What and all do you want to add in the readme?

**Comment by JuniorN1** [comment]
hi @varunwho , how are you? Welcome to API Pokemon and Digimon, in the case of the readme, initially you can make a presentation and propose of project, that would be, present data of Pokemon and Digimon, and you can add instruction clone and init project, and a message inviting if other users wanna participate, thank you for collaboration of the project

**Comment by varunwho** [comment]
Hey @JuniorN1 I'm doing good, hope you're fine too!
I'll work on it and show you the changes

**Comment by varunwho** [comment]
I'll create some templates and could you add the info on them?

**Comment by JuniorN1** [comment]
yep
