### ISSUE TITLE
Add your contribuition in readme

### ISSUE THREAD

**Issue by JuniorN1** [JuniorN1/Api-pokemon-and-digimons#20]
@varunwho , puts your participation as a contributor to the project!
I couldn't do it XD

**Comment by varunwho** [comment]
> @varunwho , puts your participation as a contributor to the project!
> I couldn't do it XD

Actually it should update automatically, idk why it's not happening. I'll try something though or else it's fine

Btw this is the code for that contributor image thing 👇

`<a href="https://github.com/JuniorN1/Api-pokemon-and-digimons/graphs/contributors">`
`<img src="https://contrib.rocks/image?repo=JuniorN1/Api-pokemon-and-digimons" />`
`</a>`
